sudo: required
language: ruby
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/tomcat
  - secure: LtBrjzjqHVxzotyQ21heEOsqWyNwVHmsc1xDSIhX+o9gISj8Tp6kSUhExrXHRVr+es1hALR5Q7Kj1+9DTfGjzTqy9mIfC/vQGo7Mvtcf2J63GE5eGbVmNoLAKl/ntvtkEA3tFi1R1Vu3eq8Y5VLV9uet59atG0ZRHlQWZqqN4BGrZD22MM8Hnxia47Lchs0XV60eq8v+5ZKazZRtoAifDeWh2Fhh190f0NXn73MoLM42fUVM7arNUtsIJi+8zFFsjdOiEQpsV6beFuxRQEnYfdTTc2OrpwwwqrBzlGPQ6tZS3sEMBoAy8mMQA6uwSMtVTZlebgr2si/q0zV96CF5A/v4D8wzjjlTuYHovLE4GOMtPBTBAKDqrEyk9d5j2UachpdqZw9ZggUhp9vuQLsiorM3AdMekCFxxfUlxKxUQj8zXD2XEr0GMZKXq+usmEQIteA8dJTzScGTjfiX1CqSWHFdhqEoMGDyqCxsaEDXSO4/HxDSHnhbjOxAo/ulIb8kLIDOvU3+bWegtmPLpXNnF4NlpHE6ykZi9gyOjLQt3kxp33o3G5OH/qsL6lheo0lo6VMlK9+KHXHuIM1dHA5LONgGSE++j55TyFMydkePEn4S9gzf3BgzYpwjr4knLRALBUTf0w+eQasFuv4qhNV6U+oYjnzcosI/xdjpbx0fRdw=
  - secure: gzAeljy7vLnuABp5ScFItK9w6+VQ19CzXyeZU52gLgzVeusoZAD1RIVapRfEqFleKQAuHMK7zT2tbnh5NEWZSIYSXk7nQRwm5clILensjqZ1KMbgJvORs1NBOlJIMymmXaLi8pbJ+j3FK8mBnBrhjO5UV35muV4pa1W+54n8DAy+i8Vs84L84LbdKIyMnFHnm3UKwMnv8h+qpRDJEhyWWlUQRs/31Yas3ynfIU7vVoYudBgZuuIE8lY81b/r1sqq9XhkfMQCCzGmYePUK0H9RYxsvTzdtCmfcABbKmQgKz0WVirT0W4b42045QSonNb76xB1A2bry+Zoxa8bf6emajwMmclv7nmAzC21apx2oiW0rsXNqX65f9b35dYrHoUyCBWhSoLa/uHZ3AotERqHEvfsGhurJF/4pX6wQ+DbUhaK76sKoH2cUZ2AJHZoV74FH7DkTf1gA1z25wQZlvr1ncxeIf5mAa1kEbnIcfyopNqfMqIu8i3z1jHCNg/VDpTVVFWoCk+2oOIqRYkbl3J/ao7cXi8zSjZjXVCjk19WLrp8eqiuBHKsDx/ake1usRS4DSgiEApB7aRhUXMiQl+gja6IB5GXuz70yD0m7HSk+ZbFEzhsiazENcL+22cz09aFcqePiZvTrTNWxrcMJfbj6MmkwDKLTPGgDrFh9AJ0VE8=
script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "8.5"; else echo $TRAVIS_BRANCH; fi`
- export REPO=dairyd/tomcat
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $REPO:$TAG
