sudo: required
language: ruby
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/tomcat
  - secure: EStMp9Xx4fv/HhPfAVURnY2vhQkFaOq1UaPvqxO8uZcJ1DoCWcez1GBk8oURaXQ0f8IiTyH/D3251IYJy6uIaGZp/T/nRhaJb5vVi24qNc8AYqycjX3dxpvg6N6nwibE1vljG38BtDwNCjh0CY9M7HqXhQc7H0DN0pv1czPJCoZR+YSpoYgxStIsTrLC2S+r22GugQmaa58e77ZA4KrwwCOiWE/8dlIWCZoMmzATBTnIrCHHTbS4UIlyI+GXNTSzaSmY4M95jk/4+0El+ggHuorIK3dQ4jOEUSePvf8JBqjqfjDszt1mX3NFGVyr0qUAmJt0LLkjv+KvT5z59qtbJfUsGDbXafcWgEKHEgFLhoZCNPsJLJDAN2+TM7lAgIrTgnS1+JXcq6fi8519fZH8PqJW+hn/6ep+5IekkNsxx/qzGBALQCrNPdO9XLKbnaXYvQEXY9JVJ6dXw2ss3/AHHi6CLHks6JDwQbqo3wQlsry2IhGngcfUI9ciiFr0xEFxR+W2IcEi4AW7MIZliUeLHTnidt2RBba/iJo1aMvlyBKpVl77OVbw1Phqvx6/0k3eeohbIRW+ayZroNWy8zmM2g/0/8vVv6gfmHp1RGW5FBi2TmvJEIpjzppS7zVjZhNuXN5bGaQFPUZymwLdtw+N1OQ83LYQxm0Y2SxcV2kzYrY=
  - secure: N0zR5Sy5shpAKiwRWk6olXWMO928eO0fLNGQBl1g6DjevtEl5u01lDKPheLN/mdved4+uROy4diXTPqQHH83h/eg9jkoZEDcPsdYzbqvo2TuIizzs6wzNfr7IQosBrkh9IfX2XxLoB0fqyoH8aC7C5PBYxT7HjyUSctKYvg7AxyfSaoqFAb7kmr2d3nSAxYCrcc+CMSoE4vJz5fs/q/OXojWMMLl9hLScIjrsmomsPzUZQaLbssFbQaxPyqS5AEjrbl8+LuMFsFqTXTKGmGTndhYLjiaGSnwG4QTcZa4mx/WmM4fT600PZ8TaPKJCvFRpOBrrlC4HUcZ+wVmorU7PmP4xtPUUSFBRtrUQLj09qo5gDSEITj1H20jeb4xBccfL0cnkM7jxKGNuRzH3etVdfVi/KUQY5ee9PVOdic4r7t7x3nKgHXF18hoGV4Jq22DRFagmo5k5lgCSu8KYUa/nfU+3r0cyfX9c7KlqWRScERPHOJrplTFqrvfRCmfcHmxmdWbFLwUQEV9V3WvMnWtj9cCK6oOKOHUztsMaXZqN3isjd7GGhZzZEZ1Ko3KfdQ+vXAi0fGYN6tGn7ocoC6n+peNU0vqDuYE+nXSFWrai86JhBJyRCGCE22qMXBCGPUT0tuBJ2sLPWnfL5Rr4NQYN0YSaQH7mXF2O9zYQKIeBm0=
script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "8.5"; else echo $TRAVIS_BRANCH; fi`
- export REPO=dairyd/tomcat
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $REPO:$TAG
